/********************************************************************************
** Form generated from reading UI file 'fileeditchild.ui'
**
** Created by: Qt User Interface Compiler version 5.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FILEEDITCHILD_H
#define UI_FILEEDITCHILD_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_FileEditChild
{
public:
    QPushButton *saveBut;
    QPushButton *editBut;
    QTextEdit *editPreviewText;
    QPushButton *saveasBut;
    QPushButton *delBut;
    QScrollBar *textpreviewScrollBar;
    QTabWidget *typeTab;
    QWidget *tab;
    QLineEdit *wordLineEdit;
    QPushButton *degreeTextRedBut;
    QLabel *fontTypeTextLab;
    QLabel *degreeTextShowLab;
    QLabel *rotateTextLab;
    QPushButton *degreeTextAddBut;
    QLabel *fontSizeTextLab;
    QLabel *internalTextLab;
    QPushButton *internalTextAddBut;
    QPushButton *internalTextRedBut;
    QLabel *internalShowTextLab;
    QComboBox *fontTypeTextComBox;
    QComboBox *fontSizeTextComBox;
    QPushButton *variableTextBut;
    QWidget *tab_3;
    QPushButton *internalTimeAddBut;
    QLabel *degreeTimeShowLab;
    QComboBox *fontSizeTimeComBox;
    QLabel *internalTimeLab;
    QPushButton *degreeTimeAddBut;
    QPushButton *internalTimeRedBut;
    QLabel *rotateTimeLab;
    QPushButton *degreeTimeRedBut;
    QPushButton *customTimeBut;
    QLabel *fontTypeTimeLab;
    QComboBox *fontTypeTimeComBox;
    QLabel *fontSizeTimeLab;
    QLabel *currentValShowTimeLab;
    QComboBox *typeTimeComBox;
    QLabel *typeTimeLab;
    QWidget *tab_4;
    QWidget *tab_5;
    QWidget *tab_6;
    QLineEdit *barCodeLineEdit;
    QLabel *zoomShowBarCodeLab;
    QPushButton *zoomBarCodeRedBut;
    QPushButton *variableBarCodeBut;
    QPushButton *degreeBarCodeRedBut;
    QComboBox *showNumBarCodeComBox;
    QPushButton *zoomBarCodeAddBut;
    QPushButton *degreeBarCodeAddBut;
    QLabel *typeBarCodeLab;
    QLabel *degreeBarCodeShowLab;
    QLabel *zoomBarCodeLab;
    QLabel *showNumBarCodeLab;
    QComboBox *typeBarCodeComBox;
    QLabel *rotateBarCodeLab;
    QPushButton *heightBarCodeAddBut;
    QLabel *heightBarCodeLab;
    QPushButton *heightBarCodeRedBut;
    QLabel *heightBarCodeShowQRLab;
    QWidget *tab_7;
    QLineEdit *QRCodeLineEdit;
    QLabel *preciseQRLab;
    QLabel *zoomShowQRLab;
    QPushButton *variableQRBut;
    QComboBox *preciseQRComBox;
    QLabel *degreeQRShowLab;
    QPushButton *degreeQRAddBut;
    QLabel *zoomQRLab;
    QComboBox *sideLenQRComBox;
    QPushButton *degreeQRRedBut;
    QLabel *rotateQRLab;
    QPushButton *zoomQRAddBut;
    QLabel *sideLenQRLab;
    QPushButton *zoomQRRedBut;
    QLabel *reverseColQRLab;
    QComboBox *reverseColQRComBox;
    QWidget *tab_2;
    QPushButton *moveUpBut;
    QPushButton *moveRightBut;
    QPushButton *moveDownBut;
    QPushButton *moveLeftBut;

    void setupUi(QWidget *FileEditChild)
    {
        if (FileEditChild->objectName().isEmpty())
            FileEditChild->setObjectName(QStringLiteral("FileEditChild"));
        FileEditChild->resize(1061, 761);
        saveBut = new QPushButton(FileEditChild);
        saveBut->setObjectName(QStringLiteral("saveBut"));
        saveBut->setGeometry(QRect(840, 430, 101, 51));
        QFont font;
        font.setFamily(QString::fromUtf8("\346\245\267\344\275\223"));
        font.setPointSize(16);
        saveBut->setFont(font);
        saveBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        editBut = new QPushButton(FileEditChild);
        editBut->setObjectName(QStringLiteral("editBut"));
        editBut->setGeometry(QRect(840, 360, 101, 51));
        editBut->setFont(font);
        editBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        editPreviewText = new QTextEdit(FileEditChild);
        editPreviewText->setObjectName(QStringLiteral("editPreviewText"));
        editPreviewText->setGeometry(QRect(10, 10, 1041, 241));
        saveasBut = new QPushButton(FileEditChild);
        saveasBut->setObjectName(QStringLiteral("saveasBut"));
        saveasBut->setGeometry(QRect(950, 430, 101, 51));
        saveasBut->setFont(font);
        saveasBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        delBut = new QPushButton(FileEditChild);
        delBut->setObjectName(QStringLiteral("delBut"));
        delBut->setGeometry(QRect(950, 360, 101, 51));
        delBut->setFont(font);
        delBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        textpreviewScrollBar = new QScrollBar(FileEditChild);
        textpreviewScrollBar->setObjectName(QStringLiteral("textpreviewScrollBar"));
        textpreviewScrollBar->setGeometry(QRect(10, 250, 1041, 26));
        textpreviewScrollBar->setStyleSheet(QStringLiteral(""));
        textpreviewScrollBar->setOrientation(Qt::Horizontal);
        typeTab = new QTabWidget(FileEditChild);
        typeTab->setObjectName(QStringLiteral("typeTab"));
        typeTab->setGeometry(QRect(10, 290, 819, 461));
        typeTab->setFont(font);
        typeTab->setStyleSheet(QLatin1String("QTabBar::tab{width:117}\n"
"QTabBar::tab{height:50}"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        wordLineEdit = new QLineEdit(tab);
        wordLineEdit->setObjectName(QStringLiteral("wordLineEdit"));
        wordLineEdit->setGeometry(QRect(10, 20, 791, 51));
        degreeTextRedBut = new QPushButton(tab);
        degreeTextRedBut->setObjectName(QStringLiteral("degreeTextRedBut"));
        degreeTextRedBut->setGeometry(QRect(160, 140, 41, 41));
        degreeTextRedBut->setMinimumSize(QSize(41, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        degreeTextRedBut->setFont(font1);
        degreeTextRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        fontTypeTextLab = new QLabel(tab);
        fontTypeTextLab->setObjectName(QStringLiteral("fontTypeTextLab"));
        fontTypeTextLab->setGeometry(QRect(440, 140, 101, 41));
        fontTypeTextLab->setMinimumSize(QSize(101, 41));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\346\245\267\344\275\223"));
        font2.setPointSize(14);
        fontTypeTextLab->setFont(font2);
        fontTypeTextLab->setAlignment(Qt::AlignCenter);
        degreeTextShowLab = new QLabel(tab);
        degreeTextShowLab->setObjectName(QStringLiteral("degreeTextShowLab"));
        degreeTextShowLab->setGeometry(QRect(200, 140, 131, 41));
        degreeTextShowLab->setMinimumSize(QSize(0, 41));
        degreeTextShowLab->setFont(font2);
        degreeTextShowLab->setAlignment(Qt::AlignCenter);
        rotateTextLab = new QLabel(tab);
        rotateTextLab->setObjectName(QStringLiteral("rotateTextLab"));
        rotateTextLab->setGeometry(QRect(60, 140, 101, 41));
        rotateTextLab->setMinimumSize(QSize(101, 41));
        rotateTextLab->setFont(font2);
        rotateTextLab->setAlignment(Qt::AlignCenter);
        degreeTextAddBut = new QPushButton(tab);
        degreeTextAddBut->setObjectName(QStringLiteral("degreeTextAddBut"));
        degreeTextAddBut->setGeometry(QRect(330, 140, 41, 41));
        degreeTextAddBut->setMinimumSize(QSize(41, 41));
        degreeTextAddBut->setFont(font1);
        degreeTextAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        fontSizeTextLab = new QLabel(tab);
        fontSizeTextLab->setObjectName(QStringLiteral("fontSizeTextLab"));
        fontSizeTextLab->setGeometry(QRect(440, 240, 101, 41));
        fontSizeTextLab->setMinimumSize(QSize(101, 41));
        fontSizeTextLab->setFont(font2);
        fontSizeTextLab->setAlignment(Qt::AlignCenter);
        internalTextLab = new QLabel(tab);
        internalTextLab->setObjectName(QStringLiteral("internalTextLab"));
        internalTextLab->setGeometry(QRect(60, 240, 101, 41));
        internalTextLab->setMinimumSize(QSize(101, 41));
        internalTextLab->setFont(font2);
        internalTextLab->setAlignment(Qt::AlignCenter);
        internalTextAddBut = new QPushButton(tab);
        internalTextAddBut->setObjectName(QStringLiteral("internalTextAddBut"));
        internalTextAddBut->setGeometry(QRect(330, 240, 41, 41));
        internalTextAddBut->setMinimumSize(QSize(41, 41));
        internalTextAddBut->setFont(font1);
        internalTextAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        internalTextRedBut = new QPushButton(tab);
        internalTextRedBut->setObjectName(QStringLiteral("internalTextRedBut"));
        internalTextRedBut->setGeometry(QRect(160, 240, 41, 41));
        internalTextRedBut->setMinimumSize(QSize(41, 41));
        internalTextRedBut->setFont(font1);
        internalTextRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        internalShowTextLab = new QLabel(tab);
        internalShowTextLab->setObjectName(QStringLiteral("internalShowTextLab"));
        internalShowTextLab->setGeometry(QRect(200, 240, 131, 41));
        internalShowTextLab->setMinimumSize(QSize(0, 41));
        internalShowTextLab->setFont(font2);
        internalShowTextLab->setAlignment(Qt::AlignCenter);
        fontTypeTextComBox = new QComboBox(tab);
        fontTypeTextComBox->setObjectName(QStringLiteral("fontTypeTextComBox"));
        fontTypeTextComBox->setGeometry(QRect(540, 145, 181, 31));
        fontTypeTextComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        fontSizeTextComBox = new QComboBox(tab);
        fontSizeTextComBox->setObjectName(QStringLiteral("fontSizeTextComBox"));
        fontSizeTextComBox->setGeometry(QRect(540, 245, 181, 31));
        fontSizeTextComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        variableTextBut = new QPushButton(tab);
        variableTextBut->setObjectName(QStringLiteral("variableTextBut"));
        variableTextBut->setGeometry(QRect(540, 330, 181, 41));
        variableTextBut->setFont(font);
        variableTextBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        typeTab->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        internalTimeAddBut = new QPushButton(tab_3);
        internalTimeAddBut->setObjectName(QStringLiteral("internalTimeAddBut"));
        internalTimeAddBut->setGeometry(QRect(340, 190, 41, 41));
        internalTimeAddBut->setMinimumSize(QSize(41, 41));
        internalTimeAddBut->setFont(font1);
        internalTimeAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        degreeTimeShowLab = new QLabel(tab_3);
        degreeTimeShowLab->setObjectName(QStringLiteral("degreeTimeShowLab"));
        degreeTimeShowLab->setGeometry(QRect(210, 90, 131, 41));
        degreeTimeShowLab->setMinimumSize(QSize(0, 41));
        degreeTimeShowLab->setFont(font2);
        degreeTimeShowLab->setAlignment(Qt::AlignCenter);
        fontSizeTimeComBox = new QComboBox(tab_3);
        fontSizeTimeComBox->setObjectName(QStringLiteral("fontSizeTimeComBox"));
        fontSizeTimeComBox->setGeometry(QRect(550, 185, 181, 31));
        fontSizeTimeComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        internalTimeLab = new QLabel(tab_3);
        internalTimeLab->setObjectName(QStringLiteral("internalTimeLab"));
        internalTimeLab->setGeometry(QRect(70, 190, 101, 41));
        internalTimeLab->setMinimumSize(QSize(101, 41));
        internalTimeLab->setFont(font2);
        internalTimeLab->setAlignment(Qt::AlignCenter);
        degreeTimeAddBut = new QPushButton(tab_3);
        degreeTimeAddBut->setObjectName(QStringLiteral("degreeTimeAddBut"));
        degreeTimeAddBut->setGeometry(QRect(340, 90, 41, 41));
        degreeTimeAddBut->setMinimumSize(QSize(41, 41));
        degreeTimeAddBut->setFont(font1);
        degreeTimeAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        internalTimeRedBut = new QPushButton(tab_3);
        internalTimeRedBut->setObjectName(QStringLiteral("internalTimeRedBut"));
        internalTimeRedBut->setGeometry(QRect(170, 190, 41, 41));
        internalTimeRedBut->setMinimumSize(QSize(41, 41));
        internalTimeRedBut->setFont(font1);
        internalTimeRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        rotateTimeLab = new QLabel(tab_3);
        rotateTimeLab->setObjectName(QStringLiteral("rotateTimeLab"));
        rotateTimeLab->setGeometry(QRect(70, 90, 101, 41));
        rotateTimeLab->setMinimumSize(QSize(101, 41));
        rotateTimeLab->setFont(font2);
        rotateTimeLab->setAlignment(Qt::AlignCenter);
        degreeTimeRedBut = new QPushButton(tab_3);
        degreeTimeRedBut->setObjectName(QStringLiteral("degreeTimeRedBut"));
        degreeTimeRedBut->setGeometry(QRect(170, 90, 41, 41));
        degreeTimeRedBut->setMinimumSize(QSize(41, 41));
        degreeTimeRedBut->setFont(font1);
        degreeTimeRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        customTimeBut = new QPushButton(tab_3);
        customTimeBut->setObjectName(QStringLiteral("customTimeBut"));
        customTimeBut->setGeometry(QRect(170, 280, 181, 41));
        customTimeBut->setFont(font);
        customTimeBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        fontTypeTimeLab = new QLabel(tab_3);
        fontTypeTimeLab->setObjectName(QStringLiteral("fontTypeTimeLab"));
        fontTypeTimeLab->setGeometry(QRect(450, 90, 101, 41));
        fontTypeTimeLab->setMinimumSize(QSize(101, 41));
        fontTypeTimeLab->setFont(font2);
        fontTypeTimeLab->setAlignment(Qt::AlignCenter);
        fontTypeTimeComBox = new QComboBox(tab_3);
        fontTypeTimeComBox->setObjectName(QStringLiteral("fontTypeTimeComBox"));
        fontTypeTimeComBox->setGeometry(QRect(550, 95, 181, 31));
        fontTypeTimeComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        fontSizeTimeLab = new QLabel(tab_3);
        fontSizeTimeLab->setObjectName(QStringLiteral("fontSizeTimeLab"));
        fontSizeTimeLab->setGeometry(QRect(450, 180, 101, 41));
        fontSizeTimeLab->setMinimumSize(QSize(101, 41));
        fontSizeTimeLab->setFont(font2);
        fontSizeTimeLab->setAlignment(Qt::AlignCenter);
        currentValShowTimeLab = new QLabel(tab_3);
        currentValShowTimeLab->setObjectName(QStringLiteral("currentValShowTimeLab"));
        currentValShowTimeLab->setGeometry(QRect(210, 190, 131, 41));
        currentValShowTimeLab->setMinimumSize(QSize(0, 41));
        currentValShowTimeLab->setFont(font2);
        currentValShowTimeLab->setAlignment(Qt::AlignCenter);
        typeTimeComBox = new QComboBox(tab_3);
        typeTimeComBox->setObjectName(QStringLiteral("typeTimeComBox"));
        typeTimeComBox->setGeometry(QRect(550, 280, 181, 31));
        typeTimeComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        typeTimeLab = new QLabel(tab_3);
        typeTimeLab->setObjectName(QStringLiteral("typeTimeLab"));
        typeTimeLab->setGeometry(QRect(450, 275, 101, 41));
        typeTimeLab->setMinimumSize(QSize(101, 41));
        typeTimeLab->setFont(font2);
        typeTimeLab->setAlignment(Qt::AlignCenter);
        typeTab->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        typeTab->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        typeTab->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        barCodeLineEdit = new QLineEdit(tab_6);
        barCodeLineEdit->setObjectName(QStringLiteral("barCodeLineEdit"));
        barCodeLineEdit->setGeometry(QRect(10, 20, 791, 51));
        zoomShowBarCodeLab = new QLabel(tab_6);
        zoomShowBarCodeLab->setObjectName(QStringLiteral("zoomShowBarCodeLab"));
        zoomShowBarCodeLab->setGeometry(QRect(210, 220, 131, 41));
        zoomShowBarCodeLab->setMinimumSize(QSize(0, 41));
        zoomShowBarCodeLab->setFont(font2);
        zoomShowBarCodeLab->setAlignment(Qt::AlignCenter);
        zoomBarCodeRedBut = new QPushButton(tab_6);
        zoomBarCodeRedBut->setObjectName(QStringLiteral("zoomBarCodeRedBut"));
        zoomBarCodeRedBut->setGeometry(QRect(170, 220, 41, 41));
        zoomBarCodeRedBut->setMinimumSize(QSize(41, 41));
        zoomBarCodeRedBut->setFont(font1);
        zoomBarCodeRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        variableBarCodeBut = new QPushButton(tab_6);
        variableBarCodeBut->setObjectName(QStringLiteral("variableBarCodeBut"));
        variableBarCodeBut->setGeometry(QRect(520, 320, 181, 41));
        variableBarCodeBut->setFont(font);
        variableBarCodeBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        degreeBarCodeRedBut = new QPushButton(tab_6);
        degreeBarCodeRedBut->setObjectName(QStringLiteral("degreeBarCodeRedBut"));
        degreeBarCodeRedBut->setGeometry(QRect(170, 120, 41, 41));
        degreeBarCodeRedBut->setMinimumSize(QSize(41, 41));
        degreeBarCodeRedBut->setFont(font1);
        degreeBarCodeRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        showNumBarCodeComBox = new QComboBox(tab_6);
        showNumBarCodeComBox->setObjectName(QStringLiteral("showNumBarCodeComBox"));
        showNumBarCodeComBox->setGeometry(QRect(550, 220, 181, 31));
        showNumBarCodeComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        zoomBarCodeAddBut = new QPushButton(tab_6);
        zoomBarCodeAddBut->setObjectName(QStringLiteral("zoomBarCodeAddBut"));
        zoomBarCodeAddBut->setGeometry(QRect(340, 220, 41, 41));
        zoomBarCodeAddBut->setMinimumSize(QSize(41, 41));
        zoomBarCodeAddBut->setFont(font1);
        zoomBarCodeAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        degreeBarCodeAddBut = new QPushButton(tab_6);
        degreeBarCodeAddBut->setObjectName(QStringLiteral("degreeBarCodeAddBut"));
        degreeBarCodeAddBut->setGeometry(QRect(340, 120, 41, 41));
        degreeBarCodeAddBut->setMinimumSize(QSize(41, 41));
        degreeBarCodeAddBut->setFont(font1);
        degreeBarCodeAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        typeBarCodeLab = new QLabel(tab_6);
        typeBarCodeLab->setObjectName(QStringLiteral("typeBarCodeLab"));
        typeBarCodeLab->setGeometry(QRect(450, 120, 101, 41));
        typeBarCodeLab->setMinimumSize(QSize(101, 41));
        typeBarCodeLab->setFont(font2);
        typeBarCodeLab->setAlignment(Qt::AlignCenter);
        degreeBarCodeShowLab = new QLabel(tab_6);
        degreeBarCodeShowLab->setObjectName(QStringLiteral("degreeBarCodeShowLab"));
        degreeBarCodeShowLab->setGeometry(QRect(210, 120, 131, 41));
        degreeBarCodeShowLab->setMinimumSize(QSize(0, 41));
        degreeBarCodeShowLab->setFont(font2);
        degreeBarCodeShowLab->setAlignment(Qt::AlignCenter);
        zoomBarCodeLab = new QLabel(tab_6);
        zoomBarCodeLab->setObjectName(QStringLiteral("zoomBarCodeLab"));
        zoomBarCodeLab->setGeometry(QRect(70, 220, 101, 41));
        zoomBarCodeLab->setMinimumSize(QSize(101, 41));
        zoomBarCodeLab->setFont(font2);
        zoomBarCodeLab->setAlignment(Qt::AlignCenter);
        showNumBarCodeLab = new QLabel(tab_6);
        showNumBarCodeLab->setObjectName(QStringLiteral("showNumBarCodeLab"));
        showNumBarCodeLab->setGeometry(QRect(450, 215, 101, 41));
        showNumBarCodeLab->setMinimumSize(QSize(101, 41));
        showNumBarCodeLab->setFont(font2);
        showNumBarCodeLab->setAlignment(Qt::AlignCenter);
        typeBarCodeComBox = new QComboBox(tab_6);
        typeBarCodeComBox->setObjectName(QStringLiteral("typeBarCodeComBox"));
        typeBarCodeComBox->setGeometry(QRect(550, 125, 181, 31));
        typeBarCodeComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        rotateBarCodeLab = new QLabel(tab_6);
        rotateBarCodeLab->setObjectName(QStringLiteral("rotateBarCodeLab"));
        rotateBarCodeLab->setGeometry(QRect(70, 120, 101, 41));
        rotateBarCodeLab->setMinimumSize(QSize(101, 41));
        rotateBarCodeLab->setFont(font2);
        rotateBarCodeLab->setAlignment(Qt::AlignCenter);
        heightBarCodeAddBut = new QPushButton(tab_6);
        heightBarCodeAddBut->setObjectName(QStringLiteral("heightBarCodeAddBut"));
        heightBarCodeAddBut->setGeometry(QRect(340, 320, 41, 41));
        heightBarCodeAddBut->setMinimumSize(QSize(41, 41));
        heightBarCodeAddBut->setFont(font1);
        heightBarCodeAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        heightBarCodeLab = new QLabel(tab_6);
        heightBarCodeLab->setObjectName(QStringLiteral("heightBarCodeLab"));
        heightBarCodeLab->setGeometry(QRect(70, 320, 101, 41));
        heightBarCodeLab->setMinimumSize(QSize(101, 41));
        heightBarCodeLab->setFont(font2);
        heightBarCodeLab->setAlignment(Qt::AlignCenter);
        heightBarCodeRedBut = new QPushButton(tab_6);
        heightBarCodeRedBut->setObjectName(QStringLiteral("heightBarCodeRedBut"));
        heightBarCodeRedBut->setGeometry(QRect(170, 320, 41, 41));
        heightBarCodeRedBut->setMinimumSize(QSize(41, 41));
        heightBarCodeRedBut->setFont(font1);
        heightBarCodeRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        heightBarCodeShowQRLab = new QLabel(tab_6);
        heightBarCodeShowQRLab->setObjectName(QStringLiteral("heightBarCodeShowQRLab"));
        heightBarCodeShowQRLab->setGeometry(QRect(210, 320, 131, 41));
        heightBarCodeShowQRLab->setMinimumSize(QSize(0, 41));
        heightBarCodeShowQRLab->setFont(font2);
        heightBarCodeShowQRLab->setAlignment(Qt::AlignCenter);
        typeTab->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        QRCodeLineEdit = new QLineEdit(tab_7);
        QRCodeLineEdit->setObjectName(QStringLiteral("QRCodeLineEdit"));
        QRCodeLineEdit->setGeometry(QRect(10, 20, 791, 51));
        preciseQRLab = new QLabel(tab_7);
        preciseQRLab->setObjectName(QStringLiteral("preciseQRLab"));
        preciseQRLab->setGeometry(QRect(450, 120, 101, 41));
        preciseQRLab->setMinimumSize(QSize(101, 41));
        preciseQRLab->setFont(font2);
        preciseQRLab->setAlignment(Qt::AlignCenter);
        zoomShowQRLab = new QLabel(tab_7);
        zoomShowQRLab->setObjectName(QStringLiteral("zoomShowQRLab"));
        zoomShowQRLab->setGeometry(QRect(210, 220, 131, 41));
        zoomShowQRLab->setMinimumSize(QSize(0, 41));
        zoomShowQRLab->setFont(font2);
        zoomShowQRLab->setAlignment(Qt::AlignCenter);
        variableQRBut = new QPushButton(tab_7);
        variableQRBut->setObjectName(QStringLiteral("variableQRBut"));
        variableQRBut->setGeometry(QRect(170, 310, 181, 41));
        variableQRBut->setFont(font);
        variableQRBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        preciseQRComBox = new QComboBox(tab_7);
        preciseQRComBox->setObjectName(QStringLiteral("preciseQRComBox"));
        preciseQRComBox->setGeometry(QRect(550, 125, 181, 31));
        preciseQRComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        degreeQRShowLab = new QLabel(tab_7);
        degreeQRShowLab->setObjectName(QStringLiteral("degreeQRShowLab"));
        degreeQRShowLab->setGeometry(QRect(210, 120, 131, 41));
        degreeQRShowLab->setMinimumSize(QSize(0, 41));
        degreeQRShowLab->setFont(font2);
        degreeQRShowLab->setAlignment(Qt::AlignCenter);
        degreeQRAddBut = new QPushButton(tab_7);
        degreeQRAddBut->setObjectName(QStringLiteral("degreeQRAddBut"));
        degreeQRAddBut->setGeometry(QRect(340, 120, 41, 41));
        degreeQRAddBut->setMinimumSize(QSize(41, 41));
        degreeQRAddBut->setFont(font1);
        degreeQRAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        zoomQRLab = new QLabel(tab_7);
        zoomQRLab->setObjectName(QStringLiteral("zoomQRLab"));
        zoomQRLab->setGeometry(QRect(70, 220, 101, 41));
        zoomQRLab->setMinimumSize(QSize(101, 41));
        zoomQRLab->setFont(font2);
        zoomQRLab->setAlignment(Qt::AlignCenter);
        sideLenQRComBox = new QComboBox(tab_7);
        sideLenQRComBox->setObjectName(QStringLiteral("sideLenQRComBox"));
        sideLenQRComBox->setGeometry(QRect(550, 215, 181, 31));
        sideLenQRComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        degreeQRRedBut = new QPushButton(tab_7);
        degreeQRRedBut->setObjectName(QStringLiteral("degreeQRRedBut"));
        degreeQRRedBut->setGeometry(QRect(170, 120, 41, 41));
        degreeQRRedBut->setMinimumSize(QSize(41, 41));
        degreeQRRedBut->setFont(font1);
        degreeQRRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        rotateQRLab = new QLabel(tab_7);
        rotateQRLab->setObjectName(QStringLiteral("rotateQRLab"));
        rotateQRLab->setGeometry(QRect(70, 120, 101, 41));
        rotateQRLab->setMinimumSize(QSize(101, 41));
        rotateQRLab->setFont(font2);
        rotateQRLab->setAlignment(Qt::AlignCenter);
        zoomQRAddBut = new QPushButton(tab_7);
        zoomQRAddBut->setObjectName(QStringLiteral("zoomQRAddBut"));
        zoomQRAddBut->setGeometry(QRect(340, 220, 41, 41));
        zoomQRAddBut->setMinimumSize(QSize(41, 41));
        zoomQRAddBut->setFont(font1);
        zoomQRAddBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        sideLenQRLab = new QLabel(tab_7);
        sideLenQRLab->setObjectName(QStringLiteral("sideLenQRLab"));
        sideLenQRLab->setGeometry(QRect(450, 210, 101, 41));
        sideLenQRLab->setMinimumSize(QSize(101, 41));
        sideLenQRLab->setFont(font2);
        sideLenQRLab->setAlignment(Qt::AlignCenter);
        zoomQRRedBut = new QPushButton(tab_7);
        zoomQRRedBut->setObjectName(QStringLiteral("zoomQRRedBut"));
        zoomQRRedBut->setGeometry(QRect(170, 220, 41, 41));
        zoomQRRedBut->setMinimumSize(QSize(41, 41));
        zoomQRRedBut->setFont(font1);
        zoomQRRedBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        reverseColQRLab = new QLabel(tab_7);
        reverseColQRLab->setObjectName(QStringLiteral("reverseColQRLab"));
        reverseColQRLab->setGeometry(QRect(450, 310, 101, 41));
        reverseColQRLab->setMinimumSize(QSize(101, 41));
        reverseColQRLab->setFont(font2);
        reverseColQRLab->setAlignment(Qt::AlignCenter);
        reverseColQRComBox = new QComboBox(tab_7);
        reverseColQRComBox->setObjectName(QStringLiteral("reverseColQRComBox"));
        reverseColQRComBox->setGeometry(QRect(550, 315, 181, 31));
        reverseColQRComBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        typeTab->addTab(tab_7, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        typeTab->addTab(tab_2, QString());
        moveUpBut = new QPushButton(FileEditChild);
        moveUpBut->setObjectName(QStringLiteral("moveUpBut"));
        moveUpBut->setGeometry(QRect(890, 530, 101, 51));
        moveUpBut->setFont(font);
        moveUpBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        moveRightBut = new QPushButton(FileEditChild);
        moveRightBut->setObjectName(QStringLiteral("moveRightBut"));
        moveRightBut->setGeometry(QRect(950, 600, 101, 51));
        moveRightBut->setFont(font);
        moveRightBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        moveDownBut = new QPushButton(FileEditChild);
        moveDownBut->setObjectName(QStringLiteral("moveDownBut"));
        moveDownBut->setGeometry(QRect(890, 670, 101, 51));
        moveDownBut->setFont(font);
        moveDownBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        moveLeftBut = new QPushButton(FileEditChild);
        moveLeftBut->setObjectName(QStringLiteral("moveLeftBut"));
        moveLeftBut->setGeometry(QRect(830, 600, 101, 51));
        moveLeftBut->setFont(font);
        moveLeftBut->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        saveBut->raise();
        editBut->raise();
        editPreviewText->raise();
        saveasBut->raise();
        delBut->raise();
        textpreviewScrollBar->raise();
        moveUpBut->raise();
        moveRightBut->raise();
        moveDownBut->raise();
        moveLeftBut->raise();
        typeTab->raise();

        retranslateUi(FileEditChild);

        typeTab->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(FileEditChild);
    } // setupUi

    void retranslateUi(QWidget *FileEditChild)
    {
        FileEditChild->setWindowTitle(QApplication::translate("FileEditChild", "FileEditChild", 0));
        saveBut->setText(QApplication::translate("FileEditChild", "\344\277\235\345\255\230", 0));
        editBut->setText(QApplication::translate("FileEditChild", "\347\274\226\350\276\221", 0));
        saveasBut->setText(QApplication::translate("FileEditChild", "\345\217\246\345\255\230\344\270\272", 0));
        delBut->setText(QApplication::translate("FileEditChild", "\345\210\240\351\231\244", 0));
        degreeTextRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        fontTypeTextLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\345\255\227\344\275\223</span></p></body></html>", 0));
        degreeTextShowLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        rotateTextLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\346\227\213\350\275\254</span></p></body></html>", 0));
        degreeTextAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        fontSizeTextLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\345\255\227\345\217\267</span></p></body></html>", 0));
        internalTextLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\351\227\264\350\267\235</span></p></body></html>", 0));
        internalTextAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        internalTextRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        internalShowTextLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        variableTextBut->setText(QApplication::translate("FileEditChild", "\345\217\257\345\217\230", 0));
        typeTab->setTabText(typeTab->indexOf(tab), QApplication::translate("FileEditChild", "\346\226\207\345\255\227", 0));
        internalTimeAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        degreeTimeShowLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        internalTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\351\227\264\350\267\235</span></p></body></html>", 0));
        degreeTimeAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        internalTimeRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        rotateTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\346\227\213\350\275\254</span></p></body></html>", 0));
        degreeTimeRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        customTimeBut->setText(QApplication::translate("FileEditChild", "\350\207\252\345\256\232\344\271\211", 0));
        fontTypeTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\345\255\227\344\275\223</span></p></body></html>", 0));
        fontSizeTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\345\255\227\345\217\267</span></p></body></html>", 0));
        currentValShowTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        typeTimeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\347\261\273\345\236\213</span></p></body></html>", 0));
        typeTab->setTabText(typeTab->indexOf(tab_3), QApplication::translate("FileEditChild", "\346\227\266\351\227\264", 0));
        typeTab->setTabText(typeTab->indexOf(tab_4), QApplication::translate("FileEditChild", "\345\272\217\345\217\267", 0));
        typeTab->setTabText(typeTab->indexOf(tab_5), QApplication::translate("FileEditChild", "\345\233\276\347\211\207", 0));
        zoomShowBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        zoomBarCodeRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        variableBarCodeBut->setText(QApplication::translate("FileEditChild", "\345\217\257\345\217\230", 0));
        degreeBarCodeRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        zoomBarCodeAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        degreeBarCodeAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        typeBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\347\261\273\345\236\213</span></p></body></html>", 0));
        degreeBarCodeShowLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        zoomBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\347\274\251\346\224\276</span></p></body></html>", 0));
        showNumBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\346\230\276\347\244\272\346\225\260\345\255\227</span></p></body></html>", 0));
        rotateBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\346\227\213\350\275\254</span></p></body></html>", 0));
        heightBarCodeAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        heightBarCodeLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\351\253\230\345\272\246</span></p></body></html>", 0));
        heightBarCodeRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        heightBarCodeShowQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        typeTab->setTabText(typeTab->indexOf(tab_6), QApplication::translate("FileEditChild", "\346\235\241\345\275\242\347\240\201", 0));
        preciseQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\347\262\276\345\272\246</span></p></body></html>", 0));
        zoomShowQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        variableQRBut->setText(QApplication::translate("FileEditChild", "\345\217\257\345\217\230", 0));
        degreeQRShowLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>", 0));
        degreeQRAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        zoomQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\347\274\251\346\224\276</span></p></body></html>", 0));
        degreeQRRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        rotateQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\346\227\213\350\275\254</span></p></body></html>", 0));
        zoomQRAddBut->setText(QApplication::translate("FileEditChild", "\357\274\213", 0));
        sideLenQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\350\276\271\351\225\277</span></p></body></html>", 0));
        zoomQRRedBut->setText(QApplication::translate("FileEditChild", "\357\274\215", 0));
        reverseColQRLab->setText(QApplication::translate("FileEditChild", "<html><head/><body><p><span style=\" color:#ffffff;\">\345\217\215\350\211\262</span></p></body></html>", 0));
        typeTab->setTabText(typeTab->indexOf(tab_7), QApplication::translate("FileEditChild", "QR\347\240\201", 0));
        typeTab->setTabText(typeTab->indexOf(tab_2), QApplication::translate("FileEditChild", "DM\347\240\201", 0));
        moveUpBut->setText(QApplication::translate("FileEditChild", "\344\270\212\347\247\273", 0));
        moveRightBut->setText(QApplication::translate("FileEditChild", "\345\217\263\347\247\273", 0));
        moveDownBut->setText(QApplication::translate("FileEditChild", "\344\270\213\347\247\273", 0));
        moveLeftBut->setText(QApplication::translate("FileEditChild", "\345\267\246\347\247\273", 0));
    } // retranslateUi

};

namespace Ui {
    class FileEditChild: public Ui_FileEditChild {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FILEEDITCHILD_H
